#!/usr/bin/perl

use Sys::Syslog qw( :DEFAULT setlogsock );

@facilities = ("kern","user","mail","daemon","auth","syslog","lpr","news","uucp","cron","security","ftp","ntp","logaudit","logalert","clock","local0","local1","local2","local3","local4","local5","local6","local7");
@severities = ("emerg","alert","crit","error","warning","notice","info","debug");

sub exitMessage {
    ($message) = @_;
    print $message;
    exit;
}

if ( ($#ARGV+1) < 2 ) { exitMessage("\nUsage apache2syslog facility_name log_level\n"); }
if ( !($ARGV[0] ~~ @facilities) ) { exitMessage("\nWrong facility: $ARGV[0] not in ".join(' ',@facilities)."\n"); }
if ( !($ARGV[1] ~~ @severities) ) { exitMessage("\nWrong severity: $ARGV[1] not in ".join(' ',@severities)."\n"); }

setlogsock('unix');
openlog('httpd', 'pid', $ARGV[0]);

while ($log = <STDIN>) {
        syslog($ARGV[1], $log);
}
closelog
